/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as InitRouteImport } from './routes/init'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ScriptsRouteImport } from './routes/scripts'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as FilesSplatRouteImport } from './routes/files/$'
import { Route as GroupGroupIdRouteImport } from './routes/group.$groupId'
import { Route as ProjectProjectIdRouteImport } from './routes/project.$projectId'
import { Route as UploadTokenRouteImport } from './routes/upload.$token'
import { Route as ApiPublicListRouteImport } from './routes/api/public/list'
import { Route as ApiPublicMetaRouteImport } from './routes/api/public/meta'
import { Route as ApiUploadLinkRouteImport } from './routes/api/upload/link'
import { Route as ApiUploadResumableRouteImport } from './routes/api/upload/resumable'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const InitRoute = InitRouteImport.update({
  id: '/init',
  path: '/init',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsRoute = ScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesSplatRoute = FilesSplatRouteImport.update({
  id: '/files/$',
  path: '/files/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupGroupIdRoute = GroupGroupIdRouteImport.update({
  id: '/group/$groupId',
  path: '/group/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadTokenRoute = UploadTokenRouteImport.update({
  id: '/upload/$token',
  path: '/upload/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicListRoute = ApiPublicListRouteImport.update({
  id: '/api/public/list',
  path: '/api/public/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetaRoute = ApiPublicMetaRouteImport.update({
  id: '/api/public/meta',
  path: '/api/public/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadLinkRoute = ApiUploadLinkRouteImport.update({
  id: '/api/upload/link',
  path: '/api/upload/link',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadResumableRoute = ApiUploadResumableRouteImport.update({
  id: '/api/upload/resumable',
  path: '/api/upload/resumable',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/groups': typeof GroupsRoute
  '/init': typeof InitRoute
  '/login': typeof LoginRoute
  '/scripts': typeof ScriptsRoute
  '/security': typeof SecurityRoute
  '/files/$': typeof FilesSplatRoute
  '/group/$groupId': typeof GroupGroupIdRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/upload/$token': typeof UploadTokenRoute
  '/api/public/list': typeof ApiPublicListRoute
  '/api/public/meta': typeof ApiPublicMetaRoute
  '/api/upload/link': typeof ApiUploadLinkRoute
  '/api/upload/resumable': typeof ApiUploadResumableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/groups': typeof GroupsRoute
  '/init': typeof InitRoute
  '/login': typeof LoginRoute
  '/scripts': typeof ScriptsRoute
  '/security': typeof SecurityRoute
  '/files/$': typeof FilesSplatRoute
  '/group/$groupId': typeof GroupGroupIdRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/upload/$token': typeof UploadTokenRoute
  '/api/public/list': typeof ApiPublicListRoute
  '/api/public/meta': typeof ApiPublicMetaRoute
  '/api/upload/link': typeof ApiUploadLinkRoute
  '/api/upload/resumable': typeof ApiUploadResumableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/archive': typeof ArchiveRoute
  '/groups': typeof GroupsRoute
  '/init': typeof InitRoute
  '/login': typeof LoginRoute
  '/scripts': typeof ScriptsRoute
  '/security': typeof SecurityRoute
  '/files/$': typeof FilesSplatRoute
  '/group/$groupId': typeof GroupGroupIdRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/upload/$token': typeof UploadTokenRoute
  '/api/public/list': typeof ApiPublicListRoute
  '/api/public/meta': typeof ApiPublicMetaRoute
  '/api/upload/link': typeof ApiUploadLinkRoute
  '/api/upload/resumable': typeof ApiUploadResumableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/archive'
    | '/groups'
    | '/init'
    | '/login'
    | '/scripts'
    | '/security'
    | '/files/$'
    | '/group/$groupId'
    | '/project/$projectId'
    | '/upload/$token'
    | '/api/public/list'
    | '/api/public/meta'
    | '/api/upload/link'
    | '/api/upload/resumable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/archive'
    | '/groups'
    | '/init'
    | '/login'
    | '/scripts'
    | '/security'
    | '/files/$'
    | '/group/$groupId'
    | '/project/$projectId'
    | '/upload/$token'
    | '/api/public/list'
    | '/api/public/meta'
    | '/api/upload/link'
    | '/api/upload/resumable'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/archive'
    | '/groups'
    | '/init'
    | '/login'
    | '/scripts'
    | '/security'
    | '/files/$'
    | '/group/$groupId'
    | '/project/$projectId'
    | '/upload/$token'
    | '/api/public/list'
    | '/api/public/meta'
    | '/api/upload/link'
    | '/api/upload/resumable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ArchiveRoute: typeof ArchiveRoute
  GroupsRoute: typeof GroupsRoute
  InitRoute: typeof InitRoute
  LoginRoute: typeof LoginRoute
  ScriptsRoute: typeof ScriptsRoute
  SecurityRoute: typeof SecurityRoute
  FilesSplatRoute: typeof FilesSplatRoute
  GroupGroupIdRoute: typeof GroupGroupIdRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
  UploadTokenRoute: typeof UploadTokenRoute
  ApiPublicListRoute: typeof ApiPublicListRoute
  ApiPublicMetaRoute: typeof ApiPublicMetaRoute
  ApiUploadLinkRoute: typeof ApiUploadLinkRoute
  ApiUploadResumableRoute: typeof ApiUploadResumableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/init': {
      id: '/init'
      path: '/init'
      fullPath: '/init'
      preLoaderRoute: typeof InitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts': {
      id: '/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof ScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/$': {
      id: '/files/$'
      path: '/files/$'
      fullPath: '/files/$'
      preLoaderRoute: typeof FilesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group/$groupId': {
      id: '/group/$groupId'
      path: '/group/$groupId'
      fullPath: '/group/$groupId'
      preLoaderRoute: typeof GroupGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload/$token': {
      id: '/upload/$token'
      path: '/upload/$token'
      fullPath: '/upload/$token'
      preLoaderRoute: typeof UploadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/list': {
      id: '/api/public/list'
      path: '/api/public/list'
      fullPath: '/api/public/list'
      preLoaderRoute: typeof ApiPublicListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta': {
      id: '/api/public/meta'
      path: '/api/public/meta'
      fullPath: '/api/public/meta'
      preLoaderRoute: typeof ApiPublicMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/link': {
      id: '/api/upload/link'
      path: '/api/upload/link'
      fullPath: '/api/upload/link'
      preLoaderRoute: typeof ApiUploadLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/resumable': {
      id: '/api/upload/resumable'
      path: '/api/upload/resumable'
      fullPath: '/api/upload/resumable'
      preLoaderRoute: typeof ApiUploadResumableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ArchiveRoute: ArchiveRoute,
  GroupsRoute: GroupsRoute,
  InitRoute: InitRoute,
  LoginRoute: LoginRoute,
  ScriptsRoute: ScriptsRoute,
  SecurityRoute: SecurityRoute,
  FilesSplatRoute: FilesSplatRoute,
  GroupGroupIdRoute: GroupGroupIdRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
  UploadTokenRoute: UploadTokenRoute,
  ApiPublicListRoute: ApiPublicListRoute,
  ApiPublicMetaRoute: ApiPublicMetaRoute,
  ApiUploadLinkRoute: ApiUploadLinkRoute,
  ApiUploadResumableRoute: ApiUploadResumableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
